auth:
  permitall:
    -
      pattern: /auth/oauth/**
    -
      pattern: /web/**

zuul:
  ribbon:
    eager-load:
      enabled: true     #zuul饥饿加载
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  routes:
    demo:
      path: /demo/**
      ignoredPatterns: /consul
      serviceId: demo
      sensitiveHeaders: Cookie,Set-Cookie
    auth:
      path: /auth/**
      ignoredPatterns: /consul
      serviceId: auth
      sensitiveHeaders: Cookie,Set-Cookie,Authentication

ribbon:
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          #strategy: SEMAPHORE
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000


security:
  oauth2:
    client:
      accessTokenUri: /oauth/token
      clientId: frontend
      clientSecret: frontend
    resource:
      id: res_apptem
     # userInfoUri: /auth/user
      token-info-uri: /oauth/check_token
  filter-order: 1

feign.hystrix.enabled: false

paascloud:
  oauth2:
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUri: ${security.oauth2.client.accessTokenUri}
      clientId: gateway
      clientSecret: gateway
      clientAuthenticationScheme: header
      clientUserName: gatewayuser
      clientPassword: password