server:
  port: 9092

spring:
  cloud:
    consul:
      discovery:
        preferIpAddress: true
        enabled: true
        register: true
        service-name: demo
        health-check-interval: 10s
        health-check-timeout: 20s
        heartbeat:
          enabled: true
        ip-address: 127.0.0.1
        port: ${server.port}
        lifecycle:
          enabled: true
        scheme: http
        prefer-agent-address: false
        register-health-check: true
        tags: master
        query-passing: true
      retry:
        initial-interval: 1000
        max-attempts: 4
        max-interval: 1000
      host: localhost
      port: 8500
  application:
    name : backend-demo
    #表示当前程序不使用sleuth
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:10000

ribbon:
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
---
spring:
  profiles: default

